name: Build packages and publish repo
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Main
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo yum install rpm-build yum-utils createrepo
      - name: Install build dependencies
        run: sudo yum-builddep SPECS/parallels-tools.spec
      - name: Build packages
        id: buld-packages
        run: rpmbuild -ba SPECS/parallels-tools.spec --define '_rpmdir docs/%{_build_arch}/Packages' --define '_srcrpmdir docs/Source/SPackages' --define '_build_name_fmt %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm'
      - name: Update repodata
        run: find docs -mindepth 1 -maxdepth 1 -type d -not -name repodata -print0 | xargs -0 -n 1 createrepo --verbose --update
      - name: Push updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git commit -m "Add ${{ github.ref }} packages and update repodata" -a
          git push
