name: Build packages and publish repo
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Main
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Install dependencies
        run: yum -y install createrepo git rpm-build yum-utils
      - name: Install build dependencies
        run: yum-builddep -y SPECS/parallels-tools.spec
      - name: Build packages
        id: buld-packages
        run: >-
          rpmbuild -ba SPECS/parallels-tools.spec
          --define "_sourcedir ${GITHUB_WORKSPACE}/SOURCES"
          --define "_rpmdir ${GITHUB_WORKSPACE}/docs/%{_build_arch}/Packages"
          --define "_srcrpmdir ${GITHUB_WORKSPACE}/docs/Source/SPackages"
          --define '_build_name_fmt %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm'
          --define "kversion $(basename $(find /usr/src/kernels -mindepth 1 -maxdepth 1 -type d) | head -n 1)"
      - name: Update repodata
        run: find docs -mindepth 1 -maxdepth 1 -type d -not -name repodata -print0 | xargs -0 -n 1 createrepo --verbose --update
      - name: Push updates
        run: |
          git config gc.auto 0
          git config --global push.default simple
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all docs
          git commit -m "Update packages and repodata"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:master
